// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/confirmation-layer/ConfirmationLayer.tsx": () => import("../components/mockups/confirmation-layer/ConfirmationLayer.tsx"),
  "./components/mockups/hakase-ai/HakaseAI.tsx": () => import("../components/mockups/hakase-ai/HakaseAI.tsx"),
  "./components/mockups/hakase-ai/MolViewer3D_Cinematic.tsx": () => import("../components/mockups/hakase-ai/MolViewer3D_Cinematic.tsx"),
  "./components/mockups/hakase-ai/MolViewer3D_Explorer.tsx": () => import("../components/mockups/hakase-ai/MolViewer3D_Explorer.tsx"),
  "./components/mockups/hakase-ai/MolViewer3D_Scientific.tsx": () => import("../components/mockups/hakase-ai/MolViewer3D_Scientific.tsx")
};
