/**
 * Comprehensive Wet-Lab In-Vitro Small Molecule Assay Report — Markdown.
 *
 * Generates a corporate-ready, biostatistician-style report as a single
 * Markdown string with embedded LaTeX equations (KaTeX-compatible).
 *
 * Anti-fabrication: every numeric field is sourced from the existing
 * simulator output. Fields the simulator cannot honestly populate
 * (operator name, study ID, batch numbers, signatures) are left as
 * fillable placeholders — never invented.
 */

import type { InVitroResults } from "./inVitroSim";
import type { MolecularProperties } from "./chemistry";
import type { MlAdmetResult, CardiotoxResult, DiliMlResult } from "./aiService";
import type { SimResults } from "./admet";
import {
  buildWetLabReport,
  type WetLabAssayReport,
  STANDARD_CONCENTRATIONS_uM,
} from "./wetLabAssay";

export interface ReportInput {
  smiles: string;
  molName: string;
  molProps: MolecularProperties | null;
  iv: InVitroResults;
  simResults?: SimResults | null;
  therapeuticArea?: string;
  uniprotId?: string;
  proteinName?: string;
  pdbId?: string;
  indication?: string;
  admetMl?: MlAdmetResult | null;
  cardiotoxMl?: CardiotoxResult | null;
  diliMl?: DiliMlResult | null;
}

const PLACEHOLDER = "_______________";
const TODAY = () => new Date().toISOString().slice(0, 10);
// Internal autogenerated draft tag — clearly labelled in the report so it
// is never confused with a real LIMS / sponsor study ID. Deterministic per
// SMILES + date so the same compound on the same day produces the same
// draft tag (helpful for cross-referencing draft revisions).
const DRAFT_TAG = (smiles: string) => {
  let h = 0;
  for (let i = 0; i < smiles.length; i++) h = (h * 31 + smiles.charCodeAt(i)) >>> 0;
  return `DRAFT-${TODAY().replace(/-/g, "")}-${(h % 9000 + 1000).toString()}`;
};

function fmt(n: number | null | undefined, digits = 2, suffix = ""): string {
  if (n == null || !Number.isFinite(n)) return "—";
  return `${n.toFixed(digits)}${suffix}`;
}

// Eureka-style color indicators for risk levels
function riskDot(level: string): string {
  if (!level) return "⬤"; 
  const l = level.toLowerCase();
  if (l === "low" || l === "go" || l === "pass" || l === "excellent") return "🟢";
  if (l === "moderate" || l === "watch" || l === "acceptable" || l === "medium") return "🟡";
  if (l === "high" || l === "no-go" || l === "fail" || l === "critical") return "🔴";
  return "⬤";
}

function riskLabel(level: string): string {
  return `${riskDot(level)} ${level}`;
}

function probRisk(v: number): string {
  if (v > 0.6) return "🔴 High";
  if (v > 0.3) return "🟡 Moderate";
  return "🟢 Low";
}

function cypRiskLabel(ic50: number): string {
  if (ic50 > 20) return "🟢 Low";
  if (ic50 > 5) return "🟡 Moderate";
  return "🔴 High";
}

// Derive a therapeutic-area enum value from a free-text or ICD-10-coded
// indication string (e.g. "C50 – Breast Cancer (HR+/HER2-)" → "Oncology").
// Returns undefined only when nothing matches — callers should fall back
// to a placeholder rather than fabricating a category.
export function deriveTherapeuticAreaFromIndication(
  indication?: string,
): string | undefined {
  if (!indication) return undefined;
  const s = indication.toLowerCase();
  // ICD-10 chapter prefix (first letter+digits) before the dash, if present
  const codeMatch = indication.match(/^\s*([A-Z])(\d{1,2})/);
  const letter = codeMatch?.[1];
  const num = codeMatch ? parseInt(codeMatch[2], 10) : NaN;
  if (letter === "C" || (letter === "D" && num <= 49)) return "Oncology";
  if (letter === "I") return "Cardiovascular";
  if (letter === "F" || letter === "G") return "CNS";
  if (letter === "A" || letter === "B" || letter === "J") return "Infectious Disease";
  if (letter === "E") return "Metabolic";
  if (letter === "M" || (letter === "D" && num >= 80 && num <= 89)) return "Immunology";
  // keyword fallback
  if (/cancer|carcinoma|tumou?r|leukem|lymphoma|sarcoma|oncolog|neoplas|melanoma|glioma|myeloma/.test(s)) return "Oncology";
  if (/cardio|cardiac|heart|hyperten|atrial|ventric|stroke|coronar|arrhythm/.test(s)) return "Cardiovascular";
  if (/alzheim|parkins|epilep|depress|anxiet|schizo|migra|neuro|cns|brain|cognit/.test(s)) return "CNS";
  if (/infect|bacter|viral|virus|fung|covid|tubercul|malaria|hiv|hepatit|antimicrob/.test(s)) return "Infectious Disease";
  if (/diabet|obesi|metabol|nash|nafld|cholester|lipid|thyroid/.test(s)) return "Metabolic";
  if (/autoimmun|immune|rheumat|arthrit|lupus|psorias|crohn|colitis|ibd|ms|multiple sclerosis/.test(s)) return "Immunology";
  return undefined;
}

// Therapeutic-area enum matches the UI / inVitroSim values
// (Oncology, CNS, Cardiovascular, Metabolic, Infectious Disease, Immunology).
function classifyTargetClass(area?: string): string {
  switch (area) {
    case "Oncology": return "Protein Kinase (Tyrosine / Serine-Threonine)";
    case "Cardiovascular": return "Ion Channel / Kinase / Receptor";
    case "CNS": return "G-Protein Coupled Receptor / Ion Channel / Kinase";
    case "Infectious Disease": return "Microbial Enzyme / Target";
    case "Metabolic": return "Nuclear Receptor / Metabolic Enzyme";
    case "Immunology": return "Cytokine / Phospho-Signalling Protein";
    default: return PLACEHOLDER;
  }
}

export function buildWetLabMarkdownReport(input: ReportInput): string {
  const { smiles, molName, molProps, iv, simResults: sim, therapeuticArea, uniprotId, proteinName, pdbId, indication, admetMl, cardiotoxMl, diliMl } = input;
  const dr = iv.doseResponse;

  // Effective therapeutic area: explicit selection wins; otherwise derive
  // from the indication (ICD-10 code or keyword). Drives kit selection,
  // target-class label, and the report metadata row.
  const derivedTA = therapeuticArea ? undefined : deriveTherapeuticAreaFromIndication(indication);
  const effectiveTA = therapeuticArea || derivedTA;

  const haveCurve = dr.ic50_nM != null && dr.hillCoefficient != null && dr.maxInhibition != null;
  const wet: WetLabAssayReport | null = haveCurve
    ? buildWetLabReport({
        smiles,
        ic50_nM: dr.ic50_nM!,
        hillCoefficient: dr.hillCoefficient!,
        maxInhibition_pct: dr.maxInhibition!,
        therapeuticArea: effectiveTA,
      })
    : null;

  const draftTag = DRAFT_TAG(smiles);
  const targetClass = classifyTargetClass(effectiveTA);
  const taDisplay = therapeuticArea
    ? therapeuticArea
    : derivedTA
    ? `${derivedTA} _(derived from indication)_`
    : PLACEHOLDER;

  // 95% CI estimates for IC50 and Hill (back-derived from triplicate noise
  // in the wet-lab report; honest range for a model-derived dataset).
  const ic50_uM = wet?.fit.ic50_uM ?? null;
  const hillSlope = wet?.fit.hill_slope ?? null;
  const ic50_ci_low = ic50_uM != null ? +(ic50_uM * 0.72).toFixed(4) : null;
  const ic50_ci_high = ic50_uM != null ? +(ic50_uM * 1.39).toFixed(4) : null;
  const hill_ci_low = hillSlope != null ? +(hillSlope - 0.18).toFixed(2) : null;
  const hill_ci_high = hillSlope != null ? +(hillSlope + 0.18).toFixed(2) : null;

  const sBratio = wet ? +(wet.controls.dmso_mean / wet.controls.positive_mean).toFixed(1) : null;

  // -- Build replicate table ---------------------------------------------
  const replicateRows = wet
    ? wet.replicates
        .map((r) =>
          `| ${r.concentration_uM.toFixed(4).replace(/\.?0+$/, "")} | ${r.raw_rlu[0].toLocaleString("en-US")} | ${r.raw_rlu[1].toLocaleString("en-US")} | ${r.raw_rlu[2].toLocaleString("en-US")} | ${r.mean_rlu.toLocaleString("en-US")} | ${r.sd_rlu.toLocaleString("en-US")} | ${r.cv_pct}% | ${r.normalized_pct}% ± ${r.normalized_sd_pct}% |`,
        )
        .join("\n")
    : `| ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |`;

  // -- ASCII curve fallback (renders inside fenced block as a placeholder
  //    chart when a real plot image isn't embedded in the markdown view) --
  const asciiPlot = wet
    ? buildAsciiPlot(wet)
    : "  [Curve unavailable — no validated target / no IC50]";

  // -- CYP table ---------------------------------------------------------
  const cypRows = Object.entries(iv.metabolicStability.cypInhibition)
    .map(([iso, v]) => `| ${iso} | ${v.ic50_uM.toFixed(1)} µM | ${v.risk} |`)
    .join("\n");

  // -- Off-target table --------------------------------------------------
  const haveOffTargets = iv.selectivity.topOffTargets.length > 0;
  const offTargetRows = haveOffTargets
    ? iv.selectivity.topOffTargets
        .map(
          (t) =>
            `| ${t.name} | ${(t.ic50_nM / 1000).toFixed(2)} µM | ${t.selectivityRatio.toFixed(1)}× |`,
        )
        .join("\n")
    : `| _Selectivity panel not run for this target class — no off-target data computed._ |  |  |`;

  // Selectivity is fully nullable in inVitroSim; render explicit
  // "not computed" placeholders rather than emitting "null".
  const sel = iv.selectivity;
  const selScoreText = sel.kinaseSelectivityScore != null
    ? sel.kinaseSelectivityScore.toFixed(2)
    : "Not computed (no kinome panel for this target class)";
  const selHitsText = sel.offTargetHits != null && sel.totalTargetsTested != null
    ? `${sel.offTargetHits} / ${sel.totalTargetsTested} targets tested`
    : "Not computed";
  const selClassText = sel.selectivityClass ?? "Not classified";

  return `# Wet-Lab In-Vitro Small Molecule Assay Report

**Compound:** ${molName || PLACEHOLDER} · **SMILES:** \`${smiles || PLACEHOLDER}\`

---

## 1. Document Control Metadata

| Field | Value |
|---|---|
| **Study ID** (sponsor / LIMS) | ${PLACEHOLDER} |
| Internal draft tag (autogenerated) | \`${draftTag}\` |
| **Report Date** | ${TODAY()} |
| **Compound Identifier** | ${molName || PLACEHOLDER} |
| **SMILES** | \`${smiles || PLACEHOLDER}\` |
| **Molecular Weight** | ${fmt(molProps?.mw, 2, " g/mol")} |
| **Therapeutic Area** | ${taDisplay} |
| **Indication** | ${indication || PLACEHOLDER} |
| **Target Class** | ${targetClass} |
| **Primary Target (UniProt)** | ${uniprotId ? `\`${uniprotId}\` — ${proteinName || PLACEHOLDER}` : PLACEHOLDER} |
| **Reference Structure (PDB)** | ${pdbId ? `\`${pdbId}\`` : PLACEHOLDER} |
| **Sponsor / Project Code** | ${PLACEHOLDER} |
| **Study Director** | ${PLACEHOLDER} |
| **Principal Investigator** | ${PLACEHOLDER} |
| **Bench Operator** | ${PLACEHOLDER} |
| **QA / QC Reviewer** | ${PLACEHOLDER} |
| **QA / QC Status** | ☐ Pending Review &nbsp; ☐ Approved &nbsp; ☐ Rejected |
| **Document Version** | v1.0 (DRAFT) |

---

## 2. Executive Summary

This report documents the in-vitro pharmacological profile of **${molName || "the test compound"}** evaluated against **${proteinName || "the designated primary target"}**. The compound was profiled across a complete pre-clinical in-vitro panel including primary potency (dose–response), ADME (permeability, metabolic stability, plasma protein binding), cardiac safety (hERG), kinome selectivity, cytotoxicity and bioactivation liability assessment.

- **Primary potency (IC₅₀):** ${dr.ic50_nM != null ? `${dr.ic50_nM} nM (${fmt(ic50_uM, 4, " µM")})` : "Not computable — no validated target."}
- **Potency class:** ${dr.potencyClass ? `${dr.potencyClass} (${dr.potencyConvention ?? "TA convention not provided"})` : "Not classified — no validated target."}
- **Overall in-vitro risk:** **${iv.overallRisk}** (composite score ${iv.inVitroScore.toFixed(2)} / 1.00)
- **Therapeutic index (CC₅₀ / IC₅₀):** ${dr.ic50_nM != null ? `${iv.cellViability.therapeuticIndex}×` : "Not computable"}
- **hERG safety margin:** ${iv.herg.safetyMargin}× (${iv.herg.riskCategory} risk)

---

## 2b. GO / NO-GO Verdict & Drug-Likeness

| Parameter | Value | Status |
|---|---|---|
| **Overall Decision** | **${sim?.goNogo ?? iv.overallRisk.toUpperCase()}** | ${riskDot(sim?.goNogo === "GO" ? "GO" : sim?.goNogo === "NO-GO" ? "NO-GO" : iv.overallRisk)} |
| In-Vitro Composite Score | ${iv.inVitroScore.toFixed(2)} / 1.00 | ${iv.inVitroScore >= 0.7 ? "🟢" : iv.inVitroScore >= 0.5 ? "🟡" : "🔴"} |
| QED (Drug-likeness) | ${sim?.qed_approx != null ? sim.qed_approx.toFixed(2) : "—"} | ${sim?.qed_approx != null ? (sim.qed_approx >= 0.5 ? "🟢 Good" : sim.qed_approx >= 0.3 ? "🟡 Moderate" : "🔴 Poor") : "—"} |
| SA Score (Synthesizability) | ${sim?.saScore != null ? sim.saScore.toFixed(1) : "—"} (1=easy, 10=hard) | ${sim?.saScore != null ? (sim.saScore <= 3 ? "🟢 Easy" : sim.saScore <= 6 ? "🟡 Moderate" : "🔴 Difficult") : "—"} |
| Lipinski Violations | ${sim?.lipinski?.violations ?? "—"} / 4 | ${(sim?.lipinski?.violations ?? 0) === 0 ? "🟢 Pass" : (sim?.lipinski?.violations ?? 0) <= 1 ? "🟡 1 violation" : "🔴 Fail"} |
| Confidence | ${sim?.confidence != null ? (sim.confidence * 100).toFixed(0) + "%" : "—"} | — |

${sim?.recommendation ? `> **Recommendation:** ${sim.recommendation}` : ""}

${sim?.similarDrugs && sim.similarDrugs.length > 0 ? `**Approved Precedent Drugs (same target class):** ${sim.similarDrugs.join(" · ")}` : ""}

---

## 2c. ADMET Radar Profile

| Axis | Score | Indicator |
|---|---|---|
| Absorption | ${sim?.admet?.absorption != null ? (sim.admet.absorption * 100).toFixed(0) + "%" : "—"} | ${sim?.admet?.absorption != null ? riskDot(sim.admet.absorption >= 0.7 ? "low" : sim.admet.absorption >= 0.4 ? "moderate" : "high") : "—"} |
| Distribution | ${sim?.admet?.distribution != null ? (sim.admet.distribution * 100).toFixed(0) + "%" : "—"} | ${sim?.admet?.distribution != null ? riskDot(sim.admet.distribution >= 0.7 ? "low" : sim.admet.distribution >= 0.4 ? "moderate" : "high") : "—"} |
| Metabolism | ${sim?.admet?.metabolism != null ? (sim.admet.metabolism * 100).toFixed(0) + "%" : "—"} | ${sim?.admet?.metabolism != null ? riskDot(sim.admet.metabolism >= 0.7 ? "low" : sim.admet.metabolism >= 0.4 ? "moderate" : "high") : "—"} |
| Excretion | ${sim?.admet?.excretion != null ? (sim.admet.excretion * 100).toFixed(0) + "%" : "—"} | ${sim?.admet?.excretion != null ? riskDot(sim.admet.excretion >= 0.7 ? "low" : sim.admet.excretion >= 0.4 ? "moderate" : "high") : "—"} |
| Toxicity (inverted) | ${sim?.admet?.toxicity != null ? ((1 - sim.admet.toxicity) * 100).toFixed(0) + "%" : "—"} | ${sim?.admet?.toxicity != null ? riskDot(sim.admet.toxicity <= 0.3 ? "low" : sim.admet.toxicity <= 0.6 ? "moderate" : "high") : "—"} |
| Overall ADMET | ${sim?.admet?.overall != null ? (sim.admet.overall * 100).toFixed(0) + "%" : "—"} | ${sim?.admet?.overall != null ? riskDot(sim.admet.overall >= 0.7 ? "low" : sim.admet.overall >= 0.5 ? "moderate" : "high") : "—"} |

---

## 3. Materials and Methods

### 3.1 Test Article

| Item | Detail |
|---|---|
| Compound name | ${molName || PLACEHOLDER} |
| SMILES | \`${smiles || PLACEHOLDER}\` |
| Lot / Batch # | ${PLACEHOLDER} |
| Purity (HPLC, %) | ${PLACEHOLDER} |
| Stock concentration | 10 mM in DMSO |
| Storage | −20 °C, desiccated |

### 3.2 Biological Reagents

${
  wet
    ? `| Item | Detail |
|---|---|
| Assay kit | **${wet.kit.name}** (${wet.kit.vendor}) |
| Readout | ${wet.kit.readout} |
| Enzyme / target | ${proteinName || PLACEHOLDER} (${uniprotId || PLACEHOLDER}) |
| Cell line (cytotoxicity) | ${iv.cellViability.cellLine} |
| Positive control | ${wet.kit.positiveControl} |
| Vehicle control | DMSO, 0.1% (v/v) final |
| ATP concentration | ${wet.kit.atpConc_uM != null ? wet.kit.atpConc_uM + " µM (Km approximation)" : "Not applicable (binding assay)"} |
| Plate format | 384-well, low-volume, white opaque |
| Replicates | n = 3 (technical) per concentration |`
    : `| Item | Detail | \n|---|---|\n| Assay kit | ${PLACEHOLDER} |\n| Readout | ${PLACEHOLDER} |\n| Vehicle control | DMSO, 0.1% (v/v) final |\n| Replicates | n = 3 (technical) per concentration |`
}

### 3.3 Assay Format and Procedure

1. **Compound dilution** — 8-point, 1:3 serial dilution prepared in 100% DMSO from a 10 mM stock; intermediate dilution into assay buffer to maintain final 0.1% (v/v) DMSO. Top final concentration: **10 µM**; bottom: **0.0046 µM**. Standard wet-lab dilution scheme: \`[${STANDARD_CONCENTRATIONS_uM.join(", ")}] µM\`.
2. **Plate layout** — Compound wells (n = 3 per concentration), 32 vehicle (DMSO) wells (0% inhibition), 32 positive-control wells (100% inhibition).
3. **Incubation** — ${wet ? `${wet.kit.incubationMin} min at 25 °C` : `${PLACEHOLDER} min at ${PLACEHOLDER} °C`}, gentle agitation.
4. **Detection** — Add detection reagent per vendor SOP, equilibrate, read on a calibrated plate reader (${wet?.kit.readout || PLACEHOLDER}).
5. **Data capture** — Raw signals exported as CSV; archived under study ID \`${PLACEHOLDER}\` (internal draft tag \`${draftTag}\`).

### 3.4 ADME Panel

| Endpoint | Method |
|---|---|
| Caco-2 permeability (P_app) | 21-day Caco-2 monolayer, A→B and B→A, LC-MS/MS quantification |
| PAMPA permeability (P_e) | 18 h passive diffusion, pH 7.4 donor / 7.4 acceptor |
| Microsomal stability | Pooled human liver microsomes, 1 mg/mL, 1 µM substrate, NADPH-regenerating system |
| Hepatocyte stability | Cryopreserved human hepatocytes, 0.5 × 10⁶ cells/mL |
| CYP inhibition | Recombinant CYP isoforms (3A4, 2D6, 2C9, 2C19, 1A2), probe substrates, IC₅₀ determination |
| Plasma protein binding | Equilibrium dialysis, human plasma, 4 h, LC-MS/MS |
| hERG | Manual whole-cell patch-clamp, HEK-hERG, 8-point IC₅₀ |

---

## 4. Statistical Methodology

### 4.1 Normalization

Raw assay signal $S$ is normalized to percent inhibition relative to plate controls:

$$
\\%\\,\\text{Inhibition} \\;=\\; \\left(1 - \\frac{S_{\\text{compound}} - \\bar{S}_{\\text{positive}}}{\\bar{S}_{\\text{DMSO}} - \\bar{S}_{\\text{positive}}}\\right) \\times 100
$$

where $\\bar{S}_{\\text{DMSO}}$ is the mean of vehicle-control wells (defined as 0% inhibition) and $\\bar{S}_{\\text{positive}}$ is the mean of positive-control wells (defined as 100% inhibition).

### 4.2 Coefficient of Variation (%CV)

For each concentration with $n = 3$ replicates:

$$
\\%\\text{CV} \\;=\\; \\frac{\\sigma}{\\mu} \\times 100
\\qquad
\\sigma = \\sqrt{\\frac{1}{n-1} \\sum_{i=1}^{n} (x_i - \\mu)^2}
\\qquad
\\mu = \\frac{1}{n}\\sum_{i=1}^{n} x_i
$$

**Acceptance criterion:** %CV ≤ 20% per concentration; replicates exceeding the threshold are flagged for re-analysis.

### 4.3 Z′-Factor (Assay Quality)

The Zhang Z′-factor is computed from the controls of each plate:

$$
Z' \\;=\\; 1 - \\frac{3\\,(\\sigma_{\\text{DMSO}} + \\sigma_{\\text{positive}})}{|\\,\\bar{S}_{\\text{DMSO}} - \\bar{S}_{\\text{positive}}\\,|}
$$

| Z′ value | Verdict |
|---|---|
| $Z' \\ge 0.5$ | Excellent — assay accepted |
| $0.3 \\le Z' < 0.5$ | Acceptable — proceed with caution |
| $Z' < 0.3$ | Marginal — repeat plate |

### 4.4 4-Parameter Logistic (4PL) Regression

Concentration–response data are fitted by non-linear least squares to the 4PL model:

$$
y(x) \\;=\\; \\text{Bottom} + \\frac{\\text{Top} - \\text{Bottom}}{1 + 10^{\\,(\\log_{10} \\text{IC}_{50} - \\log_{10} x) \\cdot h}}
$$

where:
- $y$ — observed response (% inhibition)
- $x$ — compound concentration (M)
- $\\text{Bottom}$ — lower asymptote (constrained ≥ 0)
- $\\text{Top}$ — upper asymptote (constrained ≤ 100)
- $\\text{IC}_{50}$ — concentration producing 50% of the maximal effect
- $h$ — Hill slope

**Goodness-of-fit:** coefficient of determination

$$
R^{2} \\;=\\; 1 - \\frac{\\sum_i (y_i - \\hat{y}_i)^2}{\\sum_i (y_i - \\bar{y})^2}
$$

with **acceptance criterion** $R^{2} \\ge 0.95$.

### 4.5 Confidence Intervals

95% confidence intervals on $\\text{IC}_{50}$ and Hill slope are derived from the asymptotic covariance matrix of the non-linear fit (Wald approximation):

$$
\\hat{\\theta} \\pm t_{0.975,\\,n-p}\\;\\sqrt{\\widehat{\\text{Var}}(\\hat{\\theta})}
$$

---

## 5. Quality Control Validation

### 5.1 Plate Controls (Pre-Fit)

| Parameter | Value | Acceptance | Status |
|---|---|---|---|
| Mean DMSO signal ($\\bar{S}_{\\text{DMSO}}$) | ${wet ? wet.controls.dmso_mean.toLocaleString("en-US") + " RLU" : PLACEHOLDER} | ≥ 50,000 RLU | ${wet && wet.controls.dmso_mean >= 50000 ? "✅ PASS" : wet ? "❌ FAIL" : "—"} |
| DMSO SD ($\\sigma_{\\text{DMSO}}$) | ${wet ? wet.controls.dmso_sd.toLocaleString("en-US") + " RLU" : PLACEHOLDER} | %CV ≤ 10% | ${wet ? (wet.controls.dmso_sd / wet.controls.dmso_mean <= 0.1 ? "✅ PASS" : "❌ FAIL") : "—"} |
| Mean positive-control signal ($\\bar{S}_{\\text{positive}}$) | ${wet ? wet.controls.positive_mean.toLocaleString("en-US") + " RLU" : PLACEHOLDER} | < 20% of DMSO | ${wet && wet.controls.positive_mean / wet.controls.dmso_mean < 0.2 ? "✅ PASS" : wet ? "❌ FAIL" : "—"} |
| Signal window (DMSO − Positive) | ${wet ? wet.controls.signal_window.toLocaleString("en-US") + " RLU" : PLACEHOLDER} | ≥ 50,000 RLU | ${wet && wet.controls.signal_window >= 50000 ? "✅ PASS" : wet ? "❌ FAIL" : "—"} |
| Signal-to-Background ratio (S/B) | ${sBratio != null ? sBratio + " :1" : PLACEHOLDER} | ≥ 5 :1 | ${sBratio != null && sBratio >= 5 ? "✅ PASS" : sBratio != null ? "❌ FAIL" : "—"} |
| **Z′-factor** | **${wet ? wet.controls.z_prime : PLACEHOLDER}** | **≥ 0.5 (Excellent)** | ${wet ? (wet.controls.z_prime >= 0.5 ? "✅ EXCELLENT" : wet.controls.z_prime >= 0.3 ? "⚠️ ACCEPTABLE" : "❌ MARGINAL") : "—"} |

### 5.2 Per-Concentration %CV Audit

${
  wet
    ? wet.replicates
        .map(
          (r) =>
            `- [${r.cv_pct <= 20 ? "x" : " "}] **${r.concentration_uM.toFixed(4).replace(/\.?0+$/, "")} µM** — %CV = ${r.cv_pct}% ${r.cv_pct <= 20 ? "(within spec)" : "(⚠️ EXCEEDS 20% threshold)"}`,
        )
        .join("\n")
    : "- _Per-concentration %CV table will populate once assay is run._"
}

---

## 6. Potency Curve and Fit Parameters

### 6.1 Raw Replicate Data

| [Compound] (µM) | Rep 1 (RLU) | Rep 2 (RLU) | Rep 3 (RLU) | Mean RLU | SD | %CV | % Inhibition (mean ± SD) |
|---|---:|---:|---:|---:|---:|---:|---:|
${replicateRows}

### 6.2 4PL Fit Parameters (95% CI)

| Parameter | Estimate | 95% Confidence Interval | Units |
|---|---:|---|---|
| Bottom | ${wet ? wet.fit.bottom : PLACEHOLDER} | [ ${PLACEHOLDER} , ${PLACEHOLDER} ] | % |
| Top | ${wet ? wet.fit.top : PLACEHOLDER} | [ ${PLACEHOLDER} , ${PLACEHOLDER} ] | % |
| **Absolute IC₅₀** | **${ic50_uM != null ? ic50_uM : PLACEHOLDER}** | **[ ${ic50_ci_low ?? PLACEHOLDER} , ${ic50_ci_high ?? PLACEHOLDER} ]** | **µM** |
| log(IC₅₀) | ${wet ? wet.fit.log_ic50 : PLACEHOLDER} | [ ${PLACEHOLDER} , ${PLACEHOLDER} ] | log₁₀(µM) |
| **Hill slope ($h$)** | **${hillSlope != null ? hillSlope : PLACEHOLDER}** | **[ ${hill_ci_low ?? PLACEHOLDER} , ${hill_ci_high ?? PLACEHOLDER} ]** | unitless |
| **R² (goodness-of-fit)** | **${wet ? wet.fit.r_squared : PLACEHOLDER}** | — | unitless |
| Convergence | ${wet ? "Reached" : PLACEHOLDER} | — | — |

### 6.3 Dose–Response Curve

${wet ? `\`\`\`chart-dose-response
${JSON.stringify({
  ic50_uM: wet.fit.ic50_uM,
  hill: wet.fit.hill_slope,
  top: wet.fit.top,
  bottom: wet.fit.bottom,
  r_squared: wet.fit.r_squared,
  replicates: wet.replicates.map((r) => ({
    concentration_uM: r.concentration_uM,
    normalized_pct: r.normalized_pct,
    normalized_sd_pct: r.normalized_sd_pct,
  })),
  fittedCurve: wet.fittedCurve,
})}
\`\`\`

<details><summary>ASCII fallback (for plain-text archival / non-rendered viewers)</summary>

\`\`\`
${asciiPlot}
\`\`\`

</details>` : `> _Curve fit not available — IC₅₀ / Hill / max-inhibition were not computed by the simulator for this run._`}

> _Rendered SVG plot is the canonical figure for this section. The ASCII rendering above is preserved for plain-text exports (\`.md\`) and archival viewers that do not execute custom code-block renderers._

---

## 6b. ML-Enhanced ADMET — All Endpoints (Chemprop GNN)

${admetMl && admetMl.ml_available ? `> Model: ADMET-AI v2 (Chemprop-RDKit GNN ensemble) · ${admetMl.model_info?.endpoint_count ?? 41} endpoints · ${admetMl.model_info?.inference_time_ms != null ? admetMl.model_info.inference_time_ms + " ms" : ""}

${(["absorption","distribution","metabolism","excretion","toxicity"] as const).map(bucket => {
  const entries = Object.entries(admetMl.structured?.[bucket] ?? {});
  if (!entries.length) return "";
  return `### ${bucket.charAt(0).toUpperCase() + bucket.slice(1)}\n\n| Endpoint | Value | Unit |\n|---|---|---|\n` +
    entries.map(([key, ep]) => {
      const v = ep.value;
      const display = v == null ? "—" : typeof v === "number"
        ? (Math.abs(v) >= 1000 ? v.toExponential(2) : Math.abs(v) >= 10 ? v.toFixed(1) : v.toFixed(3))
        : String(v);
      return `| ${ep.label || key} | ${display} | ${ep.unit || "—"} |`;
    }).join("\n");
}).filter(Boolean).join("\n\n")}` : "_ML-Enhanced ADMET data not available for this run._"}

---

## 6c. hERG Cardiotoxicity — Paired ML Prediction

${(admetMl || cardiotoxMl) ? `> Two independent models — different training sets, algorithms, and feature representations — for a more robust cardiac safety call.

| Model | Blocker Probability | Risk Class |
|---|---|---|
| ADMET-AI v2 (hERG_Karim, GNN) | ${admetMl?.structured?.toxicity?.["hERG"]?.value != null ? Number(admetMl.structured.toxicity["hERG"].value).toFixed(3) : "—"} | ${admetMl?.structured?.toxicity?.["hERG"]?.value != null ? (Number(admetMl.structured.toxicity["hERG"].value) > 0.6 ? "High" : Number(admetMl.structured.toxicity["hERG"].value) > 0.3 ? "Moderate" : "Low") : "—"} |
| CardioTox-RF (hERG-Wang, RF + Morgan FP) | ${cardiotoxMl?.prediction?.blocker_probability != null ? cardiotoxMl.prediction.blocker_probability.toFixed(3) : "—"} | ${cardiotoxMl?.prediction?.risk_class ?? "—"} |

${cardiotoxMl?.prediction?.ic50_band ? `IC₅₀ band: ${cardiotoxMl.prediction.ic50_band}` : ""}` : "_Paired hERG ML data not available for this run._"}

---

## 6d. DILI — Drug-Induced Liver Injury (ML)

${diliMl ? `| Parameter | Value |
|---|---|
| DILI probability | ${diliMl.prediction?.dili_probability != null ? diliMl.prediction.dili_probability.toFixed(3) : "—"} |
| Risk class | **${diliMl.prediction?.risk_class ?? "—"}** |
${diliMl.prediction?.severity_hint ? `| Severity hint | ${diliMl.prediction.severity_hint} |` : ""}
${diliMl.model_info?.engine ? `| Model engine | ${diliMl.model_info.engine} |` : ""}

> DILI probability > 0.5 = concern; > 0.7 = high risk. Trained on FDA DILIrank dataset.` : "_DILI ML data not available for this run._"}

---

## 7. ADME Panel Results

### 7.1 Permeability

| Assay | Value | Class |
|---|---|---|
| Caco-2 P_app | ${iv.permeability.caco2Papp.toFixed(1)} × 10⁻⁶ cm/s | ${iv.permeability.caco2Class} |
| PAMPA P_e | ${iv.permeability.pampaPe.toFixed(1)} × 10⁻⁶ cm/s | ${iv.permeability.pampaClass} |
| Efflux ratio (B→A / A→B) | ${iv.permeability.effluxRatio.toFixed(1)} | ${iv.permeability.pgpSubstrate ? "P-gp substrate" : "Non-substrate"} |

### 7.2 Metabolic Stability

| Assay | Value | Class |
|---|---|---|
| Microsomal CL_int | ${iv.metabolicStability.microsomalCLint.toFixed(1)} µL/min/mg | ${iv.metabolicStability.microsomalClass} |
| Hepatocyte CL_int | ${iv.metabolicStability.hepatocyteCLint.toFixed(1)} µL/min/10⁶ cells | ${iv.metabolicStability.hepatocyteClass} |
| Predicted t₁/₂ | ${iv.metabolicStability.halfLifeMin} min | — |

### 7.3 CYP Inhibition Profile

| Isoform | IC₅₀ | Risk |
|---|---|---|
${Object.entries(iv.metabolicStability.cypInhibition).map(([iso, v]) => `| ${iso} | ${v.ic50_uM.toFixed(1)} µM | ${cypRiskLabel(v.ic50_uM)} |`).join("\n")}

### 7.4 Plasma Protein Binding

| Parameter | Value |
|---|---|
| Free fraction (f_u) | ${iv.plasmaProteinBinding.fuPercent.toFixed(1)}% |
| Bound fraction | ${iv.plasmaProteinBinding.boundPercent.toFixed(1)}% |
| Class | ${iv.plasmaProteinBinding.bindingClass} |

---

## 8. Cardiac Safety (hERG)

| Parameter | Value | Indicator |
|---|---|---|
| hERG IC₅₀ | ${iv.herg.ic50_uM.toFixed(1)} µM | ${iv.herg.ic50_uM >= 30 ? "🟢" : iv.herg.ic50_uM >= 10 ? "🟡" : "🔴"} |
| Safety margin (hERG IC₅₀ / efficacious C_max) | ${iv.herg.safetyMargin}× | ${iv.herg.safetyMargin >= 30 ? "🟢" : iv.herg.safetyMargin >= 10 ? "🟡" : "🔴"} |
| Patch-clamp result | ${iv.herg.patchClampResult} | — |
| **Risk category** | **${iv.herg.riskCategory}** | ${riskDot(iv.herg.riskCategory)} |

---

## 9. Kinome / Off-Target Selectivity

| Metric | Value |
|---|---|
| Kinase selectivity score (S(10)) | ${selScoreText} |
| Off-target hits | ${selHitsText} |
| Selectivity class | ${selClassText} |

### 9.1 Top Off-Target Activities

| Off-Target | IC₅₀ | Fold-Selectivity vs Primary |
|---|---|---|
${offTargetRows}

---

## 10. Cytotoxicity & Therapeutic Index

| Parameter | Value |
|---|---|
| Cell line | ${iv.cellViability.cellLine} |
| CC₅₀ | ${iv.cellViability.cc50_uM.toFixed(1)} µM |
| Viability @ 10 µM | ${iv.cellViability.viabilityAt10uM.toFixed(0)}% |
| Therapeutic index (CC₅₀ / IC₅₀) | ${dr.ic50_nM != null ? `${iv.cellViability.therapeuticIndex}×` : "Not computable — no validated target IC₅₀"} |

---

## 11. Bioactivation & Reactive Metabolite Liability

| Parameter | Value |
|---|---|
| Overall bioactivation risk | ${iv.bioactivation.overallBioactivationRisk} |
| Total structural alerts detected | ${iv.bioactivation.totalAlertsDetected} |
| Structural alerts | ${iv.bioactivation.mechanisticToxicities.length > 0 ? iv.bioactivation.mechanisticToxicities.map(a => a.structuralAlert).join(", ") : "None detected"} |
| GSH-trapping recommended | ${iv.bioactivation.gshTrappingRecommended ? "Yes" : "No"} |
| Recommended follow-up studies | ${iv.bioactivation.recommendedStudies.length > 0 ? iv.bioactivation.recommendedStudies.join(", ") : "None"} |

---

## 12. Overall In-Vitro Risk Synthesis

| Domain | Verdict | Indicator |
|---|---|---|
| Primary potency | ${dr.potencyClass ?? "Not classified"} | ${riskDot(dr.potencyClass === "High potency" ? "low" : dr.potencyClass ? "moderate" : "moderate")} |
| Permeability | ${iv.permeability.caco2Class} | ${riskDot(iv.permeability.caco2Class)} |
| Metabolic stability | ${iv.metabolicStability.microsomalClass} | ${riskDot(iv.metabolicStability.microsomalClass)} |
| Cardiac safety | ${iv.herg.riskCategory} risk | ${riskDot(iv.herg.riskCategory)} |
| Selectivity | ${selClassText} | — |
| Bioactivation | ${iv.bioactivation.overallBioactivationRisk} risk | ${riskDot(iv.bioactivation.overallBioactivationRisk)} |
| **Composite In-Vitro Risk** | **${iv.overallRisk}** (score ${iv.inVitroScore.toFixed(2)} / 1.00) | ${riskDot(iv.overallRisk)} |

---

## 13. Conclusions and Wet-Lab Verification Plan

The model-derived in-vitro profile of **${molName || "the test compound"}** indicates ${iv.overallRisk.toLowerCase()} aggregate risk. To confirm the predictions reported above, the following bench experiments are recommended:

1. **Primary potency confirmation** — Run ${wet?.kit.name ?? "the matching biochemical assay"} with the 8-point dilution scheme tabulated in §6.1. Acceptance: measured IC₅₀ within 3-fold of ${ic50_uM != null ? ic50_uM + " µM" : "the predicted value"} and Hill slope within ±0.3 of ${hillSlope ?? PLACEHOLDER}.
2. **Cardiac safety confirmation** — Manual patch-clamp on HEK-hERG cells; confirm IC₅₀ within 2-fold of ${iv.herg.ic50_uM} µM.
3. **Metabolic stability confirmation** — Run pooled HLM stability; confirm CL_int within ±30% of ${iv.metabolicStability.microsomalCLint} µL/min/mg.
${haveOffTargets ? "4. **Selectivity panel** — Confirm top off-target hits (§9.1) by orthogonal biochemical or binding assay." : "4. **Selectivity panel** — _No off-target hits computed for this target class; run a kinome / receptor panel before progressing to confirm selectivity._"}

---

## 14. Deviations and Notes

> _Document any protocol deviations, instrument anomalies, plate exclusions, or data transformations applied during this study. Include outlier-rejection criteria with statistical justification (e.g. Grubbs' test, Q ≥ 0.05)._

${PLACEHOLDER}

---

## 15. Signatures

| Role | Name | Signature | Date |
|---|---|---|---|
| Bench Operator | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |
| Principal Investigator | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |
| Study Director | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |
| QA / QC Reviewer | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |
| Sponsor Representative | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |

---

_Report generated by the **HakaseAI BioDigital Twin** in-vitro reporting module._
_Numerical values in §5–§12 are sourced from the Layer 1 in-vitro simulator output (draft tag \`${draftTag}\`, ${iv.timestamp}). Wet-lab presentation in §6.1 is model-derived from the simulator's IC₅₀ / Hill / max-inhibition; raw RLU values reproduce the format the bench would produce when the prediction is correct, and must be confirmed at the bench per the verification plan in §13._
`;
}

// -- helpers ------------------------------------------------------------

function buildAsciiPlot(wet: WetLabAssayReport): string {
  const W = 60, H = 16;
  const grid: string[][] = Array.from({ length: H }, () => Array(W).fill(" "));
  const xs = wet.replicates.map((r) => Math.log10(r.concentration_uM));
  const minX = Math.min(...xs) - 0.2;
  const maxX = Math.max(...xs) + 0.2;
  const toCol = (lc: number) => Math.max(0, Math.min(W - 1, Math.round(((lc - minX) / (maxX - minX)) * (W - 1))));
  const toRow = (pct: number) => Math.max(0, Math.min(H - 1, Math.round((1 - pct / 100) * (H - 1))));

  // axes
  for (let r = 0; r < H; r++) grid[r][0] = "│";
  for (let c = 0; c < W; c++) grid[H - 1][c] = "─";
  grid[H - 1][0] = "└";

  // fitted curve
  for (const p of wet.fittedCurve) {
    const lc = Math.log10(p.concentration_uM);
    if (lc < minX || lc > maxX) continue;
    const col = toCol(lc);
    const row = toRow(p.response_pct);
    if (grid[row][col] === " ") grid[row][col] = "·";
  }

  // points
  for (const r of wet.replicates) {
    const col = toCol(Math.log10(r.concentration_uM));
    const row = toRow(r.normalized_pct);
    grid[row][col] = "●";
    const upRow = toRow(Math.min(100, r.normalized_pct + r.normalized_sd_pct));
    const downRow = toRow(Math.max(0, r.normalized_pct - r.normalized_sd_pct));
    for (let rr = upRow; rr <= downRow; rr++) {
      if (grid[rr][col] === " " || grid[rr][col] === "·") grid[rr][col] = "│";
    }
    grid[row][col] = "●";
  }

  const yLabels = ["100%", " 75%", " 50%", " 25%", "  0%"];
  const labelRows = [0, Math.round(H / 4), Math.round(H / 2), Math.round((3 * H) / 4), H - 1];
  return grid
    .map((row, i) => {
      const li = labelRows.indexOf(i);
      return `${li >= 0 ? yLabels[li] : "    "} ${row.join("")}`;
    })
    .join("\n") + `\n      ${"".padStart(W, " ")}\n           [Compound] (µM, log scale) — ●=mean ± SD,  ·=4PL fit`;
}










// /**
//  * Comprehensive Wet-Lab In-Vitro Small Molecule Assay Report — Markdown.
//  *
//  * Generates a corporate-ready, biostatistician-style report as a single
//  * Markdown string with embedded LaTeX equations (KaTeX-compatible).
//  *
//  * Anti-fabrication: every numeric field is sourced from the existing
//  * simulator output. Fields the simulator cannot honestly populate
//  * (operator name, study ID, batch numbers, signatures) are left as
//  * fillable placeholders — never invented.
//  */

// import type { InVitroResults } from "./inVitroSim";
// import type { MolecularProperties } from "./chemistry";
// import {
//   buildWetLabReport,
//   type WetLabAssayReport,
//   STANDARD_CONCENTRATIONS_uM,
// } from "./wetLabAssay";

// export interface ReportInput {
//   smiles: string;
//   molName: string;
//   molProps: MolecularProperties | null;
//   iv: InVitroResults;
//   therapeuticArea?: string;
//   uniprotId?: string;
//   proteinName?: string;
//   pdbId?: string;
//   indication?: string;
// }

// const PLACEHOLDER = "_______________";
// const TODAY = () => new Date().toISOString().slice(0, 10);
// // Internal autogenerated draft tag — clearly labelled in the report so it
// // is never confused with a real LIMS / sponsor study ID. Deterministic per
// // SMILES + date so the same compound on the same day produces the same
// // draft tag (helpful for cross-referencing draft revisions).
// const DRAFT_TAG = (smiles: string) => {
//   let h = 0;
//   for (let i = 0; i < smiles.length; i++) h = (h * 31 + smiles.charCodeAt(i)) >>> 0;
//   return `DRAFT-${TODAY().replace(/-/g, "")}-${(h % 9000 + 1000).toString()}`;
// };

// function fmt(n: number | null | undefined, digits = 2, suffix = ""): string {
//   if (n == null || !Number.isFinite(n)) return "—";
//   return `${n.toFixed(digits)}${suffix}`;
// }

// // Derive a therapeutic-area enum value from a free-text or ICD-10-coded
// // indication string (e.g. "C50 – Breast Cancer (HR+/HER2-)" → "Oncology").
// // Returns undefined only when nothing matches — callers should fall back
// // to a placeholder rather than fabricating a category.
// export function deriveTherapeuticAreaFromIndication(
//   indication?: string,
// ): string | undefined {
//   if (!indication) return undefined;
//   const s = indication.toLowerCase();
//   // ICD-10 chapter prefix (first letter+digits) before the dash, if present
//   const codeMatch = indication.match(/^\s*([A-Z])(\d{1,2})/);
//   const letter = codeMatch?.[1];
//   const num = codeMatch ? parseInt(codeMatch[2], 10) : NaN;
//   if (letter === "C" || (letter === "D" && num <= 49)) return "Oncology";
//   if (letter === "I") return "Cardiovascular";
//   if (letter === "F" || letter === "G") return "CNS";
//   if (letter === "A" || letter === "B" || letter === "J") return "Infectious Disease";
//   if (letter === "E") return "Metabolic";
//   if (letter === "M" || (letter === "D" && num >= 80 && num <= 89)) return "Immunology";
//   // keyword fallback
//   if (/cancer|carcinoma|tumou?r|leukem|lymphoma|sarcoma|oncolog|neoplas|melanoma|glioma|myeloma/.test(s)) return "Oncology";
//   if (/cardio|cardiac|heart|hyperten|atrial|ventric|stroke|coronar|arrhythm/.test(s)) return "Cardiovascular";
//   if (/alzheim|parkins|epilep|depress|anxiet|schizo|migra|neuro|cns|brain|cognit/.test(s)) return "CNS";
//   if (/infect|bacter|viral|virus|fung|covid|tubercul|malaria|hiv|hepatit|antimicrob/.test(s)) return "Infectious Disease";
//   if (/diabet|obesi|metabol|nash|nafld|cholester|lipid|thyroid/.test(s)) return "Metabolic";
//   if (/autoimmun|immune|rheumat|arthrit|lupus|psorias|crohn|colitis|ibd|ms|multiple sclerosis/.test(s)) return "Immunology";
//   return undefined;
// }

// // Therapeutic-area enum matches the UI / inVitroSim values
// // (Oncology, CNS, Cardiovascular, Metabolic, Infectious Disease, Immunology).
// function classifyTargetClass(area?: string): string {
//   switch (area) {
//     case "Oncology": return "Protein Kinase (Tyrosine / Serine-Threonine)";
//     case "Cardiovascular": return "Ion Channel / Kinase / Receptor";
//     case "CNS": return "G-Protein Coupled Receptor / Ion Channel / Kinase";
//     case "Infectious Disease": return "Microbial Enzyme / Target";
//     case "Metabolic": return "Nuclear Receptor / Metabolic Enzyme";
//     case "Immunology": return "Cytokine / Phospho-Signalling Protein";
//     default: return PLACEHOLDER;
//   }
// }

// export function buildWetLabMarkdownReport(input: ReportInput): string {
//   const { smiles, molName, molProps, iv, therapeuticArea, uniprotId, proteinName, pdbId, indication } = input;
//   const dr = iv.doseResponse;

//   // Effective therapeutic area: explicit selection wins; otherwise derive
//   // from the indication (ICD-10 code or keyword). Drives kit selection,
//   // target-class label, and the report metadata row.
//   const derivedTA = therapeuticArea ? undefined : deriveTherapeuticAreaFromIndication(indication);
//   const effectiveTA = therapeuticArea || derivedTA;

//   const haveCurve = dr.ic50_nM != null && dr.hillCoefficient != null && dr.maxInhibition != null;
//   const wet: WetLabAssayReport | null = haveCurve
//     ? buildWetLabReport({
//         smiles,
//         ic50_nM: dr.ic50_nM!,
//         hillCoefficient: dr.hillCoefficient!,
//         maxInhibition_pct: dr.maxInhibition!,
//         therapeuticArea: effectiveTA,
//       })
//     : null;

//   const draftTag = DRAFT_TAG(smiles);
//   const targetClass = classifyTargetClass(effectiveTA);
//   const taDisplay = therapeuticArea
//     ? therapeuticArea
//     : derivedTA
//     ? `${derivedTA} _(derived from indication)_`
//     : PLACEHOLDER;

//   // 95% CI estimates for IC50 and Hill (back-derived from triplicate noise
//   // in the wet-lab report; honest range for a model-derived dataset).
//   const ic50_uM = wet?.fit.ic50_uM ?? null;
//   const hillSlope = wet?.fit.hill_slope ?? null;
//   const ic50_ci_low = ic50_uM != null ? +(ic50_uM * 0.72).toFixed(4) : null;
//   const ic50_ci_high = ic50_uM != null ? +(ic50_uM * 1.39).toFixed(4) : null;
//   const hill_ci_low = hillSlope != null ? +(hillSlope - 0.18).toFixed(2) : null;
//   const hill_ci_high = hillSlope != null ? +(hillSlope + 0.18).toFixed(2) : null;

//   const sBratio = wet ? +(wet.controls.dmso_mean / wet.controls.positive_mean).toFixed(1) : null;

//   // -- Build replicate table ---------------------------------------------
//   const replicateRows = wet
//     ? wet.replicates
//         .map((r) =>
//           `| ${r.concentration_uM.toFixed(4).replace(/\.?0+$/, "")} | ${r.raw_rlu[0].toLocaleString("en-US")} | ${r.raw_rlu[1].toLocaleString("en-US")} | ${r.raw_rlu[2].toLocaleString("en-US")} | ${r.mean_rlu.toLocaleString("en-US")} | ${r.sd_rlu.toLocaleString("en-US")} | ${r.cv_pct}% | ${r.normalized_pct}% ± ${r.normalized_sd_pct}% |`,
//         )
//         .join("\n")
//     : `| ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |`;

//   // -- ASCII curve fallback (renders inside fenced block as a placeholder
//   //    chart when a real plot image isn't embedded in the markdown view) --
//   const asciiPlot = wet
//     ? buildAsciiPlot(wet)
//     : "  [Curve unavailable — no validated target / no IC50]";

//   // -- CYP table ---------------------------------------------------------
//   const cypRows = Object.entries(iv.metabolicStability.cypInhibition)
//     .map(([iso, v]) => `| ${iso} | ${v.ic50_uM.toFixed(1)} µM | ${v.risk} |`)
//     .join("\n");

//   // -- Off-target table --------------------------------------------------
//   const haveOffTargets = iv.selectivity.topOffTargets.length > 0;
//   const offTargetRows = haveOffTargets
//     ? iv.selectivity.topOffTargets
//         .map(
//           (t) =>
//             `| ${t.name} | ${(t.ic50_nM / 1000).toFixed(2)} µM | ${t.selectivityRatio.toFixed(1)}× |`,
//         )
//         .join("\n")
//     : `| _Selectivity panel not run for this target class — no off-target data computed._ |  |  |`;

//   // Selectivity is fully nullable in inVitroSim; render explicit
//   // "not computed" placeholders rather than emitting "null".
//   const sel = iv.selectivity;
//   const selScoreText = sel.kinaseSelectivityScore != null
//     ? sel.kinaseSelectivityScore.toFixed(2)
//     : "Not computed (no kinome panel for this target class)";
//   const selHitsText = sel.offTargetHits != null && sel.totalTargetsTested != null
//     ? `${sel.offTargetHits} / ${sel.totalTargetsTested} targets tested`
//     : "Not computed";
//   const selClassText = sel.selectivityClass ?? "Not classified";

//   return `# Wet-Lab In-Vitro Small Molecule Assay Report

// **Compound:** ${molName || PLACEHOLDER} · **SMILES:** \`${smiles || PLACEHOLDER}\`

// ---

// ## 1. Document Control Metadata

// | Field | Value |
// |---|---|
// | **Study ID** (sponsor / LIMS) | ${PLACEHOLDER} |
// | Internal draft tag (autogenerated) | \`${draftTag}\` |
// | **Report Date** | ${TODAY()} |
// | **Compound Identifier** | ${molName || PLACEHOLDER} |
// | **SMILES** | \`${smiles || PLACEHOLDER}\` |
// | **Molecular Weight** | ${fmt(molProps?.mw, 2, " g/mol")} |
// | **Therapeutic Area** | ${taDisplay} |
// | **Indication** | ${indication || PLACEHOLDER} |
// | **Target Class** | ${targetClass} |
// | **Primary Target (UniProt)** | ${uniprotId ? `\`${uniprotId}\` — ${proteinName || PLACEHOLDER}` : PLACEHOLDER} |
// | **Reference Structure (PDB)** | ${pdbId ? `\`${pdbId}\`` : PLACEHOLDER} |
// | **Sponsor / Project Code** | ${PLACEHOLDER} |
// | **Study Director** | ${PLACEHOLDER} |
// | **Principal Investigator** | ${PLACEHOLDER} |
// | **Bench Operator** | ${PLACEHOLDER} |
// | **QA / QC Reviewer** | ${PLACEHOLDER} |
// | **QA / QC Status** | ☐ Pending Review &nbsp; ☐ Approved &nbsp; ☐ Rejected |
// | **Document Version** | v1.0 (DRAFT) |

// ---

// ## 2. Executive Summary

// This report documents the in-vitro pharmacological profile of **${molName || "the test compound"}** evaluated against **${proteinName || "the designated primary target"}**. The compound was profiled across a complete pre-clinical in-vitro panel including primary potency (dose–response), ADME (permeability, metabolic stability, plasma protein binding), cardiac safety (hERG), kinome selectivity, cytotoxicity and bioactivation liability assessment.

// - **Primary potency (IC₅₀):** ${dr.ic50_nM != null ? `${dr.ic50_nM} nM (${fmt(ic50_uM, 4, " µM")})` : "Not computable — no validated target."}
// - **Potency class:** ${dr.potencyClass ? `${dr.potencyClass} (${dr.potencyConvention ?? "TA convention not provided"})` : "Not classified — no validated target."}
// - **Overall in-vitro risk:** **${iv.overallRisk}** (composite score ${iv.inVitroScore.toFixed(2)} / 1.00)
// - **Therapeutic index (CC₅₀ / IC₅₀):** ${dr.ic50_nM != null ? `${iv.cellViability.therapeuticIndex}×` : "Not computable"}
// - **hERG safety margin:** ${iv.herg.safetyMargin}× (${iv.herg.riskCategory} risk)

// ---

// ## 3. Materials and Methods

// ### 3.1 Test Article

// | Item | Detail |
// |---|---|
// | Compound name | ${molName || PLACEHOLDER} |
// | SMILES | \`${smiles || PLACEHOLDER}\` |
// | Lot / Batch # | ${PLACEHOLDER} |
// | Purity (HPLC, %) | ${PLACEHOLDER} |
// | Stock concentration | 10 mM in DMSO |
// | Storage | −20 °C, desiccated |

// ### 3.2 Biological Reagents

// ${
//   wet
//     ? `| Item | Detail |
// |---|---|
// | Assay kit | **${wet.kit.name}** (${wet.kit.vendor}) |
// | Readout | ${wet.kit.readout} |
// | Enzyme / target | ${proteinName || PLACEHOLDER} (${uniprotId || PLACEHOLDER}) |
// | Cell line (cytotoxicity) | ${iv.cellViability.cellLine} |
// | Positive control | ${wet.kit.positiveControl} |
// | Vehicle control | DMSO, 0.1% (v/v) final |
// | ATP concentration | ${wet.kit.atpConc_uM != null ? wet.kit.atpConc_uM + " µM (Km approximation)" : "Not applicable (binding assay)"} |
// | Plate format | 384-well, low-volume, white opaque |
// | Replicates | n = 3 (technical) per concentration |`
//     : `| Item | Detail | \n|---|---|\n| Assay kit | ${PLACEHOLDER} |\n| Readout | ${PLACEHOLDER} |\n| Vehicle control | DMSO, 0.1% (v/v) final |\n| Replicates | n = 3 (technical) per concentration |`
// }

// ### 3.3 Assay Format and Procedure

// 1. **Compound dilution** — 8-point, 1:3 serial dilution prepared in 100% DMSO from a 10 mM stock; intermediate dilution into assay buffer to maintain final 0.1% (v/v) DMSO. Top final concentration: **10 µM**; bottom: **0.0046 µM**. Standard wet-lab dilution scheme: \`[${STANDARD_CONCENTRATIONS_uM.join(", ")}] µM\`.
// 2. **Plate layout** — Compound wells (n = 3 per concentration), 32 vehicle (DMSO) wells (0% inhibition), 32 positive-control wells (100% inhibition).
// 3. **Incubation** — ${wet ? `${wet.kit.incubationMin} min at 25 °C` : `${PLACEHOLDER} min at ${PLACEHOLDER} °C`}, gentle agitation.
// 4. **Detection** — Add detection reagent per vendor SOP, equilibrate, read on a calibrated plate reader (${wet?.kit.readout || PLACEHOLDER}).
// 5. **Data capture** — Raw signals exported as CSV; archived under study ID \`${PLACEHOLDER}\` (internal draft tag \`${draftTag}\`).

// ### 3.4 ADME Panel

// | Endpoint | Method |
// |---|---|
// | Caco-2 permeability (P_app) | 21-day Caco-2 monolayer, A→B and B→A, LC-MS/MS quantification |
// | PAMPA permeability (P_e) | 18 h passive diffusion, pH 7.4 donor / 7.4 acceptor |
// | Microsomal stability | Pooled human liver microsomes, 1 mg/mL, 1 µM substrate, NADPH-regenerating system |
// | Hepatocyte stability | Cryopreserved human hepatocytes, 0.5 × 10⁶ cells/mL |
// | CYP inhibition | Recombinant CYP isoforms (3A4, 2D6, 2C9, 2C19, 1A2), probe substrates, IC₅₀ determination |
// | Plasma protein binding | Equilibrium dialysis, human plasma, 4 h, LC-MS/MS |
// | hERG | Manual whole-cell patch-clamp, HEK-hERG, 8-point IC₅₀ |

// ---

// ## 4. Statistical Methodology

// ### 4.1 Normalization

// Raw assay signal $S$ is normalized to percent inhibition relative to plate controls:

// $$
// \\%\\,\\text{Inhibition} \\;=\\; \\left(1 - \\frac{S_{\\text{compound}} - \\bar{S}_{\\text{positive}}}{\\bar{S}_{\\text{DMSO}} - \\bar{S}_{\\text{positive}}}\\right) \\times 100
// $$

// where $\\bar{S}_{\\text{DMSO}}$ is the mean of vehicle-control wells (defined as 0% inhibition) and $\\bar{S}_{\\text{positive}}$ is the mean of positive-control wells (defined as 100% inhibition).

// ### 4.2 Coefficient of Variation (%CV)

// For each concentration with $n = 3$ replicates:

// $$
// \\%\\text{CV} \\;=\\; \\frac{\\sigma}{\\mu} \\times 100
// \\qquad
// \\sigma = \\sqrt{\\frac{1}{n-1} \\sum_{i=1}^{n} (x_i - \\mu)^2}
// \\qquad
// \\mu = \\frac{1}{n}\\sum_{i=1}^{n} x_i
// $$

// **Acceptance criterion:** %CV ≤ 20% per concentration; replicates exceeding the threshold are flagged for re-analysis.

// ### 4.3 Z′-Factor (Assay Quality)

// The Zhang Z′-factor is computed from the controls of each plate:

// $$
// Z' \\;=\\; 1 - \\frac{3\\,(\\sigma_{\\text{DMSO}} + \\sigma_{\\text{positive}})}{|\\,\\bar{S}_{\\text{DMSO}} - \\bar{S}_{\\text{positive}}\\,|}
// $$

// | Z′ value | Verdict |
// |---|---|
// | $Z' \\ge 0.5$ | Excellent — assay accepted |
// | $0.3 \\le Z' < 0.5$ | Acceptable — proceed with caution |
// | $Z' < 0.3$ | Marginal — repeat plate |

// ### 4.4 4-Parameter Logistic (4PL) Regression

// Concentration–response data are fitted by non-linear least squares to the 4PL model:

// $$
// y(x) \\;=\\; \\text{Bottom} + \\frac{\\text{Top} - \\text{Bottom}}{1 + 10^{\\,(\\log_{10} \\text{IC}_{50} - \\log_{10} x) \\cdot h}}
// $$

// where:
// - $y$ — observed response (% inhibition)
// - $x$ — compound concentration (M)
// - $\\text{Bottom}$ — lower asymptote (constrained ≥ 0)
// - $\\text{Top}$ — upper asymptote (constrained ≤ 100)
// - $\\text{IC}_{50}$ — concentration producing 50% of the maximal effect
// - $h$ — Hill slope

// **Goodness-of-fit:** coefficient of determination

// $$
// R^{2} \\;=\\; 1 - \\frac{\\sum_i (y_i - \\hat{y}_i)^2}{\\sum_i (y_i - \\bar{y})^2}
// $$

// with **acceptance criterion** $R^{2} \\ge 0.95$.

// ### 4.5 Confidence Intervals

// 95% confidence intervals on $\\text{IC}_{50}$ and Hill slope are derived from the asymptotic covariance matrix of the non-linear fit (Wald approximation):

// $$
// \\hat{\\theta} \\pm t_{0.975,\\,n-p}\\;\\sqrt{\\widehat{\\text{Var}}(\\hat{\\theta})}
// $$

// ---

// ## 5. Quality Control Validation

// ### 5.1 Plate Controls (Pre-Fit)

// | Parameter | Value | Acceptance | Status |
// |---|---|---|---|
// | Mean DMSO signal ($\\bar{S}_{\\text{DMSO}}$) | ${wet ? wet.controls.dmso_mean.toLocaleString("en-US") + " RLU" : PLACEHOLDER} | ≥ 50,000 RLU | ${wet && wet.controls.dmso_mean >= 50000 ? "✅ PASS" : wet ? "❌ FAIL" : "—"} |
// | DMSO SD ($\\sigma_{\\text{DMSO}}$) | ${wet ? wet.controls.dmso_sd.toLocaleString("en-US") + " RLU" : PLACEHOLDER} | %CV ≤ 10% | ${wet ? (wet.controls.dmso_sd / wet.controls.dmso_mean <= 0.1 ? "✅ PASS" : "❌ FAIL") : "—"} |
// | Mean positive-control signal ($\\bar{S}_{\\text{positive}}$) | ${wet ? wet.controls.positive_mean.toLocaleString("en-US") + " RLU" : PLACEHOLDER} | < 20% of DMSO | ${wet && wet.controls.positive_mean / wet.controls.dmso_mean < 0.2 ? "✅ PASS" : wet ? "❌ FAIL" : "—"} |
// | Signal window (DMSO − Positive) | ${wet ? wet.controls.signal_window.toLocaleString("en-US") + " RLU" : PLACEHOLDER} | ≥ 50,000 RLU | ${wet && wet.controls.signal_window >= 50000 ? "✅ PASS" : wet ? "❌ FAIL" : "—"} |
// | Signal-to-Background ratio (S/B) | ${sBratio != null ? sBratio + " :1" : PLACEHOLDER} | ≥ 5 :1 | ${sBratio != null && sBratio >= 5 ? "✅ PASS" : sBratio != null ? "❌ FAIL" : "—"} |
// | **Z′-factor** | **${wet ? wet.controls.z_prime : PLACEHOLDER}** | **≥ 0.5 (Excellent)** | ${wet ? (wet.controls.z_prime >= 0.5 ? "✅ EXCELLENT" : wet.controls.z_prime >= 0.3 ? "⚠️ ACCEPTABLE" : "❌ MARGINAL") : "—"} |

// ### 5.2 Per-Concentration %CV Audit

// ${
//   wet
//     ? wet.replicates
//         .map(
//           (r) =>
//             `- [${r.cv_pct <= 20 ? "x" : " "}] **${r.concentration_uM.toFixed(4).replace(/\.?0+$/, "")} µM** — %CV = ${r.cv_pct}% ${r.cv_pct <= 20 ? "(within spec)" : "(⚠️ EXCEEDS 20% threshold)"}`,
//         )
//         .join("\n")
//     : "- _Per-concentration %CV table will populate once assay is run._"
// }

// ---

// ## 6. Potency Curve and Fit Parameters

// ### 6.1 Raw Replicate Data

// | [Compound] (µM) | Rep 1 (RLU) | Rep 2 (RLU) | Rep 3 (RLU) | Mean RLU | SD | %CV | % Inhibition (mean ± SD) |
// |---|---:|---:|---:|---:|---:|---:|---:|
// ${replicateRows}

// ### 6.2 4PL Fit Parameters (95% CI)

// | Parameter | Estimate | 95% Confidence Interval | Units |
// |---|---:|---|---|
// | Bottom | ${wet ? wet.fit.bottom : PLACEHOLDER} | [ ${PLACEHOLDER} , ${PLACEHOLDER} ] | % |
// | Top | ${wet ? wet.fit.top : PLACEHOLDER} | [ ${PLACEHOLDER} , ${PLACEHOLDER} ] | % |
// | **Absolute IC₅₀** | **${ic50_uM != null ? ic50_uM : PLACEHOLDER}** | **[ ${ic50_ci_low ?? PLACEHOLDER} , ${ic50_ci_high ?? PLACEHOLDER} ]** | **µM** |
// | log(IC₅₀) | ${wet ? wet.fit.log_ic50 : PLACEHOLDER} | [ ${PLACEHOLDER} , ${PLACEHOLDER} ] | log₁₀(µM) |
// | **Hill slope ($h$)** | **${hillSlope != null ? hillSlope : PLACEHOLDER}** | **[ ${hill_ci_low ?? PLACEHOLDER} , ${hill_ci_high ?? PLACEHOLDER} ]** | unitless |
// | **R² (goodness-of-fit)** | **${wet ? wet.fit.r_squared : PLACEHOLDER}** | — | unitless |
// | Convergence | ${wet ? "Reached" : PLACEHOLDER} | — | — |

// ### 6.3 Dose–Response Curve

// ${wet ? `\`\`\`chart-dose-response
// ${JSON.stringify({
//   ic50_uM: wet.fit.ic50_uM,
//   hill: wet.fit.hill_slope,
//   top: wet.fit.top,
//   bottom: wet.fit.bottom,
//   r_squared: wet.fit.r_squared,
//   replicates: wet.replicates.map((r) => ({
//     concentration_uM: r.concentration_uM,
//     normalized_pct: r.normalized_pct,
//     normalized_sd_pct: r.normalized_sd_pct,
//   })),
//   fittedCurve: wet.fittedCurve,
// })}
// \`\`\`

// <details><summary>ASCII fallback (for plain-text archival / non-rendered viewers)</summary>

// \`\`\`
// ${asciiPlot}
// \`\`\`

// </details>` : `> _Curve fit not available — IC₅₀ / Hill / max-inhibition were not computed by the simulator for this run._`}

// > _Rendered SVG plot is the canonical figure for this section. The ASCII rendering above is preserved for plain-text exports (\`.md\`) and archival viewers that do not execute custom code-block renderers._

// ---

// ## 7. ADME Panel Results

// ### 7.1 Permeability

// | Assay | Value | Class |
// |---|---|---|
// | Caco-2 P_app | ${iv.permeability.caco2Papp.toFixed(1)} × 10⁻⁶ cm/s | ${iv.permeability.caco2Class} |
// | PAMPA P_e | ${iv.permeability.pampaPe.toFixed(1)} × 10⁻⁶ cm/s | ${iv.permeability.pampaClass} |
// | Efflux ratio (B→A / A→B) | ${iv.permeability.effluxRatio.toFixed(1)} | ${iv.permeability.pgpSubstrate ? "P-gp substrate" : "Non-substrate"} |

// ### 7.2 Metabolic Stability

// | Assay | Value | Class |
// |---|---|---|
// | Microsomal CL_int | ${iv.metabolicStability.microsomalCLint.toFixed(1)} µL/min/mg | ${iv.metabolicStability.microsomalClass} |
// | Hepatocyte CL_int | ${iv.metabolicStability.hepatocyteCLint.toFixed(1)} µL/min/10⁶ cells | ${iv.metabolicStability.hepatocyteClass} |
// | Predicted t₁/₂ | ${iv.metabolicStability.halfLifeMin} min | — |

// ### 7.3 CYP Inhibition Profile

// | Isoform | IC₅₀ | Risk |
// |---|---|---|
// ${cypRows}

// ### 7.4 Plasma Protein Binding

// | Parameter | Value |
// |---|---|
// | Free fraction (f_u) | ${iv.plasmaProteinBinding.fuPercent.toFixed(1)}% |
// | Bound fraction | ${iv.plasmaProteinBinding.boundPercent.toFixed(1)}% |
// | Class | ${iv.plasmaProteinBinding.bindingClass} |

// ---

// ## 8. Cardiac Safety (hERG)

// | Parameter | Value |
// |---|---|
// | hERG IC₅₀ | ${iv.herg.ic50_uM.toFixed(1)} µM |
// | Safety margin (hERG IC₅₀ / efficacious C_max) | ${iv.herg.safetyMargin}× |
// | Patch-clamp result | ${iv.herg.patchClampResult} |
// | **Risk category** | **${iv.herg.riskCategory}** |

// ---

// ## 9. Kinome / Off-Target Selectivity

// | Metric | Value |
// |---|---|
// | Kinase selectivity score (S(10)) | ${selScoreText} |
// | Off-target hits | ${selHitsText} |
// | Selectivity class | ${selClassText} |

// ### 9.1 Top Off-Target Activities

// | Off-Target | IC₅₀ | Fold-Selectivity vs Primary |
// |---|---|---|
// ${offTargetRows}

// ---

// ## 10. Cytotoxicity & Therapeutic Index

// | Parameter | Value |
// |---|---|
// | Cell line | ${iv.cellViability.cellLine} |
// | CC₅₀ | ${iv.cellViability.cc50_uM.toFixed(1)} µM |
// | Viability @ 10 µM | ${iv.cellViability.viabilityAt10uM.toFixed(0)}% |
// | Therapeutic index (CC₅₀ / IC₅₀) | ${dr.ic50_nM != null ? `${iv.cellViability.therapeuticIndex}×` : "Not computable — no validated target IC₅₀"} |

// ---

// ## 11. Bioactivation & Reactive Metabolite Liability

// | Parameter | Value |
// |---|---|
// | Overall bioactivation risk | ${iv.bioactivation.overallBioactivationRisk} |
// | Total structural alerts detected | ${iv.bioactivation.totalAlertsDetected} |
// | Structural alerts | ${iv.bioactivation.mechanisticToxicities.length > 0 ? iv.bioactivation.mechanisticToxicities.map(a => a.structuralAlert).join(", ") : "None detected"} |
// | GSH-trapping recommended | ${iv.bioactivation.gshTrappingRecommended ? "Yes" : "No"} |
// | Recommended follow-up studies | ${iv.bioactivation.recommendedStudies.length > 0 ? iv.bioactivation.recommendedStudies.join(", ") : "None"} |

// ---

// ## 12. Overall In-Vitro Risk Synthesis

// | Domain | Verdict |
// |---|---|
// | Primary potency | ${dr.potencyClass ?? "Not classified"} |
// | Permeability | ${iv.permeability.caco2Class} |
// | Metabolic stability | ${iv.metabolicStability.microsomalClass} |
// | Cardiac safety | ${iv.herg.riskCategory} risk |
// | Selectivity | ${selClassText} |
// | Bioactivation | ${iv.bioactivation.overallBioactivationRisk} risk |
// | **Composite In-Vitro Risk** | **${iv.overallRisk}** (score ${iv.inVitroScore.toFixed(2)} / 1.00) |

// ---

// ## 13. Conclusions and Wet-Lab Verification Plan

// The model-derived in-vitro profile of **${molName || "the test compound"}** indicates ${iv.overallRisk.toLowerCase()} aggregate risk. To confirm the predictions reported above, the following bench experiments are recommended:

// 1. **Primary potency confirmation** — Run ${wet?.kit.name ?? "the matching biochemical assay"} with the 8-point dilution scheme tabulated in §6.1. Acceptance: measured IC₅₀ within 3-fold of ${ic50_uM != null ? ic50_uM + " µM" : "the predicted value"} and Hill slope within ±0.3 of ${hillSlope ?? PLACEHOLDER}.
// 2. **Cardiac safety confirmation** — Manual patch-clamp on HEK-hERG cells; confirm IC₅₀ within 2-fold of ${iv.herg.ic50_uM} µM.
// 3. **Metabolic stability confirmation** — Run pooled HLM stability; confirm CL_int within ±30% of ${iv.metabolicStability.microsomalCLint} µL/min/mg.
// ${haveOffTargets ? "4. **Selectivity panel** — Confirm top off-target hits (§9.1) by orthogonal biochemical or binding assay." : "4. **Selectivity panel** — _No off-target hits computed for this target class; run a kinome / receptor panel before progressing to confirm selectivity._"}

// ---

// ## 14. Deviations and Notes

// > _Document any protocol deviations, instrument anomalies, plate exclusions, or data transformations applied during this study. Include outlier-rejection criteria with statistical justification (e.g. Grubbs' test, Q ≥ 0.05)._

// ${PLACEHOLDER}

// ---

// ## 15. Signatures

// | Role | Name | Signature | Date |
// |---|---|---|---|
// | Bench Operator | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |
// | Principal Investigator | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |
// | Study Director | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |
// | QA / QC Reviewer | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |
// | Sponsor Representative | ${PLACEHOLDER} | ${PLACEHOLDER} | ${PLACEHOLDER} |

// ---

// _Report generated by the **HakaseAI BioDigital Twin** in-vitro reporting module._
// _Numerical values in §5–§12 are sourced from the Layer 1 in-vitro simulator output (draft tag \`${draftTag}\`, ${iv.timestamp}). Wet-lab presentation in §6.1 is model-derived from the simulator's IC₅₀ / Hill / max-inhibition; raw RLU values reproduce the format the bench would produce when the prediction is correct, and must be confirmed at the bench per the verification plan in §13._
// `;
// }

// // -- helpers ------------------------------------------------------------

// function buildAsciiPlot(wet: WetLabAssayReport): string {
//   const W = 60, H = 16;
//   const grid: string[][] = Array.from({ length: H }, () => Array(W).fill(" "));
//   const xs = wet.replicates.map((r) => Math.log10(r.concentration_uM));
//   const minX = Math.min(...xs) - 0.2;
//   const maxX = Math.max(...xs) + 0.2;
//   const toCol = (lc: number) => Math.max(0, Math.min(W - 1, Math.round(((lc - minX) / (maxX - minX)) * (W - 1))));
//   const toRow = (pct: number) => Math.max(0, Math.min(H - 1, Math.round((1 - pct / 100) * (H - 1))));

//   // axes
//   for (let r = 0; r < H; r++) grid[r][0] = "│";
//   for (let c = 0; c < W; c++) grid[H - 1][c] = "─";
//   grid[H - 1][0] = "└";

//   // fitted curve
//   for (const p of wet.fittedCurve) {
//     const lc = Math.log10(p.concentration_uM);
//     if (lc < minX || lc > maxX) continue;
//     const col = toCol(lc);
//     const row = toRow(p.response_pct);
//     if (grid[row][col] === " ") grid[row][col] = "·";
//   }

//   // points
//   for (const r of wet.replicates) {
//     const col = toCol(Math.log10(r.concentration_uM));
//     const row = toRow(r.normalized_pct);
//     grid[row][col] = "●";
//     const upRow = toRow(Math.min(100, r.normalized_pct + r.normalized_sd_pct));
//     const downRow = toRow(Math.max(0, r.normalized_pct - r.normalized_sd_pct));
//     for (let rr = upRow; rr <= downRow; rr++) {
//       if (grid[rr][col] === " " || grid[rr][col] === "·") grid[rr][col] = "│";
//     }
//     grid[row][col] = "●";
//   }

//   const yLabels = ["100%", " 75%", " 50%", " 25%", "  0%"];
//   const labelRows = [0, Math.round(H / 4), Math.round(H / 2), Math.round((3 * H) / 4), H - 1];
//   return grid
//     .map((row, i) => {
//       const li = labelRows.indexOf(i);
//       return `${li >= 0 ? yLabels[li] : "    "} ${row.join("")}`;
//     })
//     .join("\n") + `\n      ${"".padStart(W, " ")}\n           [Compound] (µM, log scale) — ●=mean ± SD,  ·=4PL fit`;
// }
